//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Function : Node
{
    private FunctionBody body;
    public Variable resultValue;
    public List<Variable> argVars;

    public Function(FunctionBody body, params Value[] oldVars)
    {
        this.body = body;
        this.name = body.functionName;

        /*
        resultValue = new Variable(this, "res");

        argVars = new List<Variable>();
        for (int i = 0; i < oldVars.Length; i++ )
        {
            argVars.Add(new Variable(this, "arg"+(i+1)));
        }
         * */
    }

    public override string ToString()
    {
        return print(0);
    }

    public override string print(int o)
    {
        return name;
    }

    public override void execute()
    {
        /*
        Memory.getInstance().pushFunction(this);
        body.execute();
        Memory.getInstance().popFunction();
         * */
    }
}


