//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using FlutterCConsole;

public class While : Node
{
    public Node condition;
    public Node body;

    public While(Node host) {
        this.name = host.name +"$"+ NameInventor.makeBlockName("w");
    }

    public void setStuff(Node condition, Node body){
        this.condition = condition;
        this.body = body;
    }

    public override string print(int o)
    {
        string res = "";;
        res += new string(' ', o)+"while (" + "):\n";
        res += body.print(o+Settings.OFFSET);
        return res;
    }

    public override string ToString()
    {
        return print(0);
    }

    public override void execute()
    {
        int i = 0;
        while(true){
            if(Memory.getInstance().functionReturnFlag){
                break;
            }

            if (Memory.getInstance().breakFlag)
            {
                break;
            }

            condition.execute();

            Value r = Memory.getInstance().peek();
            if (r.value == 0)
            {
                break;
            }
            else
            {
                body.execute();
            }
            i++;

            if(i>100000000){
                throw new EndlessLoopException();
            }
        }
    }
}

