//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using FlutterCConsole;

public class Variable
{
    public Stack<Value> values;
    public string longname;
    public string typetoken;

    public Variable(Node f, string shortName, Value val) {
        longname = f.name + "$" + shortName;
        values = new Stack<Value>();
        this.typetoken = val.typetoken;
        values.Push(val);
    }

    public void Push()
    {
        Value newValue = new Value(typetoken, true);
        values.Push(newValue);
    }

    public Value get()
    {
        return values.Peek();
    }

    public void Pop()
    {
        values.Pop();
    }

    public void free()
    {
        Memory.getInstance().cellMemory.free(values.Peek().address);
    }

    public override string ToString()
    {
        string res =  longname;
        return res;
    }
}

